export const ADD_TVSHOW_INFOS = 'ADD_TVSHOW_INFOS';

export const ADD_TVSHOW_EPISODES = 'ADD_TVSHOW_EPISODES';

export const ADD_TVSHOW_SEASONS = 'ADD_TVSHOW_SEASONS';

export const ADD_TVSHOW_CAST = 'ADD_TVSHOW_CAST';

export const ADD_EPISODE_DETAILS = 'ADD_EPISODE_DETAILS';
